name: Cypress Test

on: [push]

test:
    name: Cypress Integration Tests
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          working-directory: e2e
          config: baseUrl=http://devopse22.4a4b.dk
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
